- type: "mqtt"
  name: "cloud_mqtt"
  enable: true
  broker: "tcp://127.0.0.1:18083"
  client_id: "edge001"
  username: "user"
  password: "pass"
  topic: "edge/data"

- type: "http"
  name: "webapi_push"
  enable: false
  url: "http://192.168.1.230/api/v1/telemetry"
  method: "POST"
  headers:
    Authorization: "Bearer xxx"
