# BACnet 设备点位物模型配置示例
- device_id: "bacnet_sim_1"
  protocol: "bacnet"
  protocol_name: "bacnet_sim_1"
  functions:
    - function: "analogInput"   # 模拟量输入点
      points:
        - address: "1"
          name: "room_temp"
          type: "float"
          property: "presentValue"
          property_value_type: "REAL"
          unit: "℃"
          transform: "value * 1.0"
          format: "Float AB CD"
          writable: false
        - address: "2"
          name: "humidity"
          type: "float"
          property: "presentValue"
          property_value_type: "REAL"
          unit: "%RH"
          transform: "value * 1.0"
          format: "Float AB CD"
          writable: false
        - address: "3"
          name: "co2"
          type: "int"
          property: "presentValue"
          property_value_type: "INTEGER"
          unit: "ppm"
          transform: ""
          format: "INT"
          writable: false
        - address: "4"
          name: "pm2_5"
          type: "int"
          property: "presentValue"
          property_value_type: "INTEGER"
          unit: "ug/m3"
          transform: ""
          format: "INT"
          writable: false
    - function: "binaryInput"    # 开关量输入点
      points:
        - address: "1"
          name: "smoke_alarm"
          type: "bool"
          property: "presentValue"
          property_value_type: "BOOLEAN"
          unit: ""
          transform: ""
          format: "BOOL"
          writable: false
        - address: "2"
          name: "occupancy"
          type: "bool"
          property: "presentValue"
          property_value_type: "BOOLEAN"
          unit: ""
          transform: ""
          format: "BOOL"
          writable: false
        - address: "3"
          name: "window_open"
          type: "bool"
          property: "presentValue"
          property_value_type: "BOOLEAN"
          unit: ""
          transform: ""
          format: "BOOL"
          writable: false
    - function: "analogValue"    # 模拟量设定值/可写点
      points:
        - address: "1"
          name: "setpoint"
          type: "float"
          property: "presentValue"
          property_value_type: "REAL"
          unit: "℃"
          transform: ""
          format: "Float AB CD"
          writable: true
        - address: "2"
          name: "fan_speed"
          type: "int"
          property: "presentValue"
          property_value_type: "INTEGER"
          unit: "rpm"
          transform: ""
          format: "INT"
          writable: true
        - address: "3"
          name: "valve_position"
          type: "float"
          property: "presentValue"
          property_value_type: "REAL"
          unit: "%"
          transform: ""
          format: "Float AB CD"
          writable: true
