# 设备清单
- id: sensor_modbus_1
  name: "Modbus Sensor"
  protocol: modbus
  protocol_name: default_tcp
  interval: 5s
  enable_ping: true
  description: "Modbus TCP device"
  ip: 127.0.0.1
  port: 502
  slave_id: 1   # 确保这个字段存在
- id: sensor_modbus_2
  name: "Modbus Sensor"
  protocol: modbus
  protocol_name: default_tcp
  interval: 5s
  enable_ping: true
  description: "Modbus TCP device"
  ip: 127.0.0.1
  port: 502
  slave_id: 2   # 确保这个字段存在
