- device_id: "sensor_modbus_1"
  aggregate:
    - point: "temp_1"
      description: "统计温度平均值"
      method: "avg"
      window: 5
  alarm:
    - point: "temp_1"
      description: "温度传感器高温报警"
      condition: "value > 50.0"
      level: "warning"
      message: "高温报警"
    - point: "temp_2"
      description: "温度传感器高温报警"
      condition: "value > 50.0"
      level: "warning"
      message: "高温报警"

- device_id: "sensor_modbus_2"
  alarm:
    - point: "temp_3"
      description: "温度传感器高温报警"
      condition: "value > 50.0"
      level: "warning"
      message: "温度传感器2 高温报警"
  linkage:
    - source_point: "temp_3"
      description: "高温报警→打开风机"
      condition: "value > 50.0"
      action_device: "sensor_modbus_1"
      action_address: "temp_10"
      action_value: 19
