# 批量温度点位配置示例
- device_id: "sensor_modbus_1"
  protocol: "modbus_tcp"
  protocol_name: "modbus_tcp_name_1"
  functions:
    - function: "03"
      points:
        - address: "40001"
          name: "temp_1"
          type: "float64"
          unit: "℃"
          transform: ""
          format: "Float AB CD"
        - address: "40003"
          name: "temp_3"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40004"
          name: "temp_4"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40005"
          name: "temp_5"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40006"
          name: "temp_6"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40007"
          name: "temp_7"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40008"
          name: "temp_8"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40009"
          name: "temp_9"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40010"
          name: "temp_10"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40011"
          name: "temp_11"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40012"
          name: "temp_12"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40013"
          name: "temp_13"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40015"
          name: "temp_15"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40016"
          name: "temp_16"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40017"
          name: "temp_17"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40018"
          name: "temp_18"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40019"
          name: "temp_19"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40020"
          name: "temp_20"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40021"
          name: "temp_21"
          type: "int"
          unit: "℃"
          transform: "value"
          format: "INT"
    - function: "01"
      points:
        - address: "10001"
          name: "sw_1"
          type: "bool"
          unit: ""
          transform: ""
          format: "bool"
- device_id: "sensor_modbus_2"
  protocol: "modbus_tcp"
  protocol_name: "modbus_tcp_name_1"
  functions:
    - function: "03"
      points:
        - address: "40001"
          quantity: 1 # 偏移量
           # 读取数量
           # 注意：如果是批量读取，address需要从40001开始，quantity可以设置为8
           # 如果是单个读取，address可以直接设置为40001，quantity设置为1
           # 这里假设每个传感器有8个温度点位
           # 如果需要更多点位，可以继续添加
           # 注意：如果使用批量读取，address需要从40001开始，quantity可以设置为8
          name: "temp_1"
          type: "int"
          unit: "℃"
          transform: ""
          format:  "int"
        - address: "40002"
          name: "temp_2"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40003"
          name: "temp_3"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40004"
          name: "temp_4"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40005"
          name: "temp_5"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40006"
          name: "temp_6"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40007"
          name: "temp_7"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"
        - address: "40008"
          name: "temp_8"
          type: "int"
          unit: "℃"
          transform: "value * 0.1"
          format: "INT"