# 协议参数示例
modbus:
  port: COM1
  baudrate: 9600
modbus_tcp:
  ip:127.0.0.1
  port: COM1
  baudrate: 9600
s7:
  ip: 192.168.0.1
  rack: 0
  slot: 1
mqtt:
  broker: tcp://localhost:1883
  topic: sensor/data
